server:
  port: 8090
  tomcat:
    uri-encoding: utf-8


spring:
  data:
    mongodb:
      host: "127.0.0.1"
      port: 27017
      database: "LogCenter"
      username: "LogCenterAdmin"
      password: "LogCenterAdmin"

